MyEquip app Inquiry flow
equiphealth/equip-health-automation-framework pull request #1
Opened 2021-12-29 11:37 UTC by balakrishna-deema

@chandhuequip please review the scripts of Inquiry flow step1 and step2 and let me know if any changes/updated required

2022-01-03 15:34 UTC, chandhuequip approved these changes

2022-01-05 16:17 UTC, chandhuequip requested changes

2022-01-05 16:17 UTC, chandhuequip commented on src/com/equip/eaf/tests/MyEquip_Inquiry_MySelf.java
> +	@Test (priority=1, groups={"Smoke", "Regression", "Functional"})
@balakrishna-deema As Discussed, can you add the DESC and Groups to all test methods in this class. Also see if you can add the testcase id in the desc and method for each test we are running.

2022-01-05 16:17 UTC, chandhuequip commented on src/com/equip/eaf/base/LoginConstants.java
> +		ENVIRONMENT = System.getProperty("Environment");
@balakrishna-deema Looks like you updated the script instead of just replacing it with mine. I think we can delete this class since we have created a separate class yesterday

2022-01-05 16:23 UTC, balakrishna-deema commented on src/com/equip/eaf/base/LoginConstants.java
> +		ENVIRONMENT = System.getProperty("Environment");
sure @chandhuequip , i will replace the content with yours

2022-01-06 08:34 UTC, balakrishna-deema commented on src/com/equip/eaf/tests/MyEquip.java
> +		getDriver().get("https://dev-my.equip.health/");
Done

2022-01-06 08:35 UTC, balakrishna-deema commented on src/com/equip/eaf/tests/MyEquip.java
> +	 @Test (priority=1)
added test test case ids, description and groups to the tests

2022-01-06 08:35 UTC, balakrishna-deema commented on src/com/equip/eaf/base/LoginConstants.java
> +		ENVIRONMENT = System.getProperty("Environment");
done

2022-01-06 15:19 UTC, chandhuequip approved these changes

2022-01-06 15:25 UTC, merged